CREATE TABLE users (
  id BIGINT NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NULL,
  plan VARCHAR(20) NOT NULL DEFAULT 'FREE',
  locale VARCHAR(10) NOT NULL DEFAULT 'en',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY uk_users_email (email)
);

CREATE TABLE boards (
  id BIGINT NOT NULL AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  name VARCHAR(80) NOT NULL,
  board_type VARCHAR(20) NOT NULL,
  color VARCHAR(20) NOT NULL DEFAULT '#12A150',
  block_shape VARCHAR(20) NOT NULL DEFAULT 'SQUARE',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id), KEY idx_boards_user (user_id),
  CONSTRAINT fk_boards_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE pixel_entries (
  id BIGINT NOT NULL AUTO_INCREMENT,
  board_id BIGINT NOT NULL,
  entry_date DATE NOT NULL,
  numeric_value DECIMAL(12,2) NULL,
  success BOOLEAN NULL,
  emoji VARCHAR(16) NULL,
  note VARCHAR(280) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id), UNIQUE KEY uk_entries_board_date (board_id, entry_date),
  KEY idx_entries_date (entry_date),
  CONSTRAINT fk_entries_board FOREIGN KEY (board_id) REFERENCES boards(id) ON DELETE CASCADE
);
